spring.application.name=School Booking Platform Backend
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8080
spring.liquibase.enabled=true

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
magic-link.expiration-time=${MAGIC_LINK_EXPIRATION_TIME}
magic-link.secret=${MAGIC_LINK_SECRET}
magic-link.base-url=${MAGIC_LINK_BASE_URL}
magic-link.frontend-endpoint=${MAGIC_LINK_FRONTEND_ENDPOINT}
magic-link.paramName=${MAGIC_LINK_PARAM_NAME}
